version: '1.0'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DOCKER_POSTGRES_DB}
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
